### ISSUE TITLE
Unclear privacy and security requirement

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-add/draft-ietf-add-svcb-dns#16]
[Section 8.1.2](https://datatracker.ietf.org/doc/html/draft-ietf-add-svcb-dns-02#section-8.1.2) currently says:

```
DNS services that are
   identified by a hostname ([Section 3](https://datatracker.ietf.org/doc/html/draft-ietf-add-svcb-dns-02#section-3)) MUST ensure that all
   unauthenticated DNS requests to that name receive any promised
   privacy and security guarantees, regardless of transport, port
   number, or HTTP path.
```

This MUST seems strange. Is this just saying "don't do silly or otherwise bad things with client queries"? I'm not sure that's something we need normative language for here, so unless there's a particular behavior that this is meant to require (or prohibit), I'd recommend removing it.

**Comment by bemasc** [comment]
Suppose `https://example.com/dns-query{?dns}` is your consumer-facing endpoint with limited logging, and "https://example.com/debug{?dns}" is a debug endpoint that drops all queries into a log that's accessible to your whole engineering staff.  The point of this sentence is that, if this is your configuration, you can't promise users the limited logging on the consumer-facing endpoint, because any intermediary could flip users onto the debug endpoint, causing you to violate your own promise.  You need to move these endpoints onto separate hostnames.  Separate paths, port numbers, or even separate ALPNs, is not sufficient, because an attacker can steer the user between them.

**Comment by chris-box** [comment]
I agree the original text was unclear unless you're already familiar with the problem. I wasn't. However Ben's response above DID make sense to me, so it would be good to use some of it.
